// Route to Permission mapping for access control
export const routePermissions: Record<string, string> = {
  '/dashboard/home': 'view-dashboard',
  '/dashboard/appointments': 'view-appointments',
  '/dashboard/patients': 'view-patients',
  '/dashboard/doctors': 'view-doctors',
  '/dashboard/departments': 'view-departments',
  '/dashboard/staff': 'view-staff',
  '/dashboard/prescriptions': 'view-prescriptions',
  '/dashboard/medical-records': 'view-medical-records',
  '/dashboard/patient-reports': 'view-patient-reports',
  '/dashboard/bills': 'view-bills',
  '/dashboard/billing': 'view-billing-finance',
  '/dashboard/medicines': 'view-medicines',
  '/dashboard/pharmacy': 'view-pharmacy',
  '/dashboard/laboratory': 'view-laboratory',
  '/dashboard/inventory': 'view-inventory',
  '/dashboard/rooms': 'view-rooms',
  '/dashboard/schedules': 'view-schedules',
  '/dashboard/emergency': 'view-emergency',
  '/dashboard/services': 'view-services',
  '/dashboard/gallery': 'view-gallery',
  '/dashboard/testimonials': 'view-testimonials',
  '/dashboard/faq': 'view-faq',
  '/dashboard/contact-inquiries': 'view-contact-inquiries',
  '/dashboard/reports': 'view-reports',
  '/dashboard/settings': 'view-settings',
  '/dashboard/roles': 'view-roles',
  '/dashboard/permissions': 'view-permissions',
  '/dashboard/role-permissions': 'manage-roles',
  '/dashboard/user-roles': 'assign-roles',
  '/dashboard/profile': 'view-profile',
  '/dashboard/notifications': 'view-notifications',
};

